stages:
  - test

.linux-test:
  stage: test
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install --yes cmake ninja-build $C_COMPILER
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=$CC -DWG_BUILD_WIN32=OFF -DWG_WARNINGS_AS_ERRORS=ON
    - cmake --build build
    - ctest --test-dir build --output-on-failure

gcc:
  extends: .linux-test
  variables:
    C_COMPILER: gcc
    CC: gcc

clang:
  extends: .linux-test
  variables:
    C_COMPILER: clang
    CC: clang

sanitizers:
  stage: test
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install --yes clang cmake ninja-build
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang -DWG_BUILD_WIN32=OFF -DWG_WARNINGS_AS_ERRORS=ON -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined"
    - cmake --build build
    - ctest --test-dir build --output-on-failure
