# Mirrored in wolf3d-lib and wolf3d-portable. Keep compatible with CMake 3.5.
# Vocabulary and extension rules: docs/BUILD-NAMING.md.

function(wg_distribution out product version backend root dist_root)
    if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Release CACHE STRING "Build configuration" FORCE)
    endif()
    foreach(configuration ${CMAKE_CONFIGURATION_TYPES} ${CMAKE_BUILD_TYPE})
        if(NOT configuration MATCHES "^(Release|Debug|RelWithDebInfo|MinSizeRel)$")
            message(FATAL_ERROR "Add distribution vocabulary for configuration ${configuration}")
        endif()
    endforeach()
    string(REGEX MATCH "^[0-9]+" major "${CMAKE_C_COMPILER_VERSION}")
    if(MSVC)
        if(MSVC_VERSION EQUAL 1200)
            set(toolchain msvc-6.0)
        elseif(MSVC_VERSION EQUAL 1300)
            set(toolchain msvc-7.0)
        elseif(MSVC_VERSION EQUAL 1310)
            set(toolchain msvc-7.1)
        elseif(MSVC_TOOLSET_VERSION)
            set(toolchain "msvc-v${MSVC_TOOLSET_VERSION}")
        elseif(MSVC_VERSION EQUAL 1400)
            set(toolchain msvc-v80)
        else()
            message(FATAL_ERROR "Unrecognized MSVC toolset; extend WGDistribution.cmake")
        endif()
    elseif(MINGW)
        # Profiles provide their CRT explicitly. Native MSYS2 UCRT presets
        # retain their old label as an input for backwards compatibility.
        set(crt "${WG_DIST_CRT}")
        if(NOT crt)
            if("${WG_COMPILER_LABEL};${W3P_COMPILER_LABEL}" MATCHES "ucrt")
                set(crt ucrt)
            elseif("${WG_COMPILER_LABEL};${W3P_COMPILER_LABEL}" MATCHES "mingw-gcc|msvcrt")
                set(crt msvcrt)
            else()
                message(FATAL_ERROR "Set WG_DIST_CRT to msvcrt or ucrt for this MinGW toolchain")
            endif()
        endif()
        if(NOT crt MATCHES "^(msvcrt|ucrt)$")
            message(FATAL_ERROR "Invalid WG_DIST_CRT: ${crt}")
        endif()
        if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
            set(toolchain "mingw-gcc${major}-${crt}")
        elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
            set(toolchain "llvm-mingw${major}-${crt}")
        else()
            message(FATAL_ERROR "Unsupported MinGW compiler: ${CMAKE_C_COMPILER_ID}")
        endif()
    elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
        set(toolchain "gcc${major}")
    elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
        set(toolchain "clang${major}")
    else()
        message(FATAL_ERROR "Add distribution vocabulary for ${CMAKE_C_COMPILER_ID}")
    endif()

    # Generator platform identifies the target, even on a different host CPU.
    set(cpu "${CMAKE_SYSTEM_PROCESSOR}")
    if(CMAKE_VS_PLATFORM_NAME)
        set(cpu "${CMAKE_VS_PLATFORM_NAME}")
    endif()
    if(CMAKE_GENERATOR_PLATFORM)
        set(cpu "${CMAKE_GENERATOR_PLATFORM}")
    endif()
    string(TOLOWER "${cpu}" cpu)
    if(cpu MATCHES "arm64|aarch64")
        set(arch arm64)
    elseif(cpu MATCHES "arm")
        message(FATAL_ERROR "Unsupported distribution architecture: ${cpu}")
    elseif(NOT cpu MATCHES "^(amd64|x86_64|x64|x86|i[3-6]86|win32)$")
        message(FATAL_ERROR "Unsupported distribution architecture: ${cpu}")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(arch x64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(arch x86)
    else()
        message(FATAL_ERROR "Unknown distribution architecture")
    endif()

    set(platform "${WG_DIST_PLATFORM}")
    if(NOT platform)
        if(WIN32)
            if(CMAKE_VS_PLATFORM_TOOLSET MATCHES "_xp$" OR (MSVC AND MSVC_VERSION LESS 1601))
                set(platform winxp)
            elseif(MSVC AND MSVC_VERSION LESS 1920)
                set(platform win7)
            else()
                set(platform win10)
            endif()
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            if(WG_LINUX_LIBC)
                set(platform "linux-${WG_LINUX_LIBC}")
            else()
                # Detect the target libc, including native Alpine builds.
                include(CheckCSourceCompiles)
                check_c_source_compiles("#include <features.h>\n#ifndef __GLIBC__\n#error not glibc\n#endif\nint main(void) { return 0; }" WG_DIST_HAS_GLIBC)
                if(WG_DIST_HAS_GLIBC)
                    set(platform linux-glibc)
                else()
                    message(FATAL_ERROR "Set WG_LINUX_LIBC=musl for musl; unknown libc must not be mislabeled")
                endif()
            endif()
        else()
            message(FATAL_ERROR "Add distribution vocabulary for ${CMAKE_SYSTEM_NAME}")
        endif()
    endif()
    if(NOT platform MATCHES "^(win9x|winxp|win7|win10|linux-glibc|linux-musl)$")
        message(FATAL_ERROR "Invalid WG_DIST_PLATFORM: ${platform}")
    endif()
    if(WIN32 AND backend STREQUAL "sdl3" AND NOT platform MATCHES "^(win7|win10)$")
        message(FATAL_ERROR "SDL3 has no supported ${platform} distribution profile")
    endif()
    if(NOT backend MATCHES "^(|gdi|sdl3|kms-fbdev)$")
        message(FATAL_ERROR "Invalid distribution backend: ${backend}")
    endif()
    set(name "${product}_${version}_${platform}_${arch}")
    if(backend)
        set(name "${name}_${backend}")
    endif()
    set(name "${name}_${toolchain}")
    # Generator expressions work with VS multi-config and CMake 3.5.
    set(config "$<CONFIG>")
    set(name "${name}$<$<CONFIG:Debug>:_debug>$<$<CONFIG:RelWithDebInfo>:_relwithdebinfo>$<$<CONFIG:MinSizeRel>:_minsizerel>")
    set(runtime "default")
    if(MSVC)
        set(runtime static-crt)
        if(NOT WG_STATIC_MSVC_RUNTIME)
            set(runtime dynamic-crt)
            set(name "${name}_dynamic-crt")
        endif()
    elseif(MINGW)
        set(runtime static-gcc-runtime)
        if(NOT WG_STATIC_GNU_RUNTIME)
            set(runtime dynamic-gcc-runtime)
            set(name "${name}_dynamic-gcc-runtime")
        endif()
    endif()
    set(directory "${dist_root}/${name}")
    set(${out} "${directory}" PARENT_SCOPE)
    set(${out}_ARCH "${arch}" PARENT_SCOPE)
    set(info "${CMAKE_CURRENT_BINARY_DIR}/${out}-$<CONFIG>-BUILD-INFO.txt")
    set(${out}_INFO "${info}" PARENT_SCOPE)
    foreach(driver NUKED DBOPL SILENT ADLIB)
        if(NOT DEFINED WG_ENABLE_OPL_${driver})
            set(WG_ENABLE_OPL_${driver} OFF)
        endif()
    endforeach()
    set(config_flags "$<$<CONFIG:Debug>:${CMAKE_C_FLAGS_DEBUG}>$<$<CONFIG:Release>:${CMAKE_C_FLAGS_RELEASE}>$<$<CONFIG:RelWithDebInfo>:${CMAKE_C_FLAGS_RELWITHDEBINFO}>$<$<CONFIG:MinSizeRel>:${CMAKE_C_FLAGS_MINSIZEREL}>")
    set(content "Product: ${product}\nVersion: ${version}\nPlatform baseline: ${platform}\nArchitecture: ${arch}\nBackend: ${backend}\nToolchain: ${toolchain}\nCompiler: ${CMAKE_C_COMPILER}\nCompiler version: ${CMAKE_C_COMPILER_VERSION}\nMSVC toolset: ${CMAKE_VS_PLATFORM_TOOLSET}\nConfiguration: ${config}\nCompiler runtime: ${runtime}\nC flags: ${CMAKE_C_FLAGS} ${config_flags}\nOPL drivers: nuked=${WG_ENABLE_OPL_NUKED}, dbopl=${WG_ENABLE_OPL_DBOPL}, silent=${WG_ENABLE_OPL_SILENT}, adlib=${WG_ENABLE_OPL_ADLIB}\nDefault OPL driver: ${WG_DEFAULT_OPL_DRIVER}\nPreferred sample rate: ${WG_DEFAULT_SAMPLE_RATE} Hz\n")
    file(GENERATE OUTPUT "${info}" CONTENT "${content}")
    # Consumers read this, rather than trying to predict compiler versions.
    file(RELATIVE_PATH relative "${root}" "${dist_root}")
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${out}-$<CONFIG>.path"
        CONTENT "${relative}/${name}\n")
endfunction()

# Record target settings that are not necessarily represented in the cache.
# Keep expressions verbatim here; the summary above records active config.
function(wg_distribution_target_info root)
    set(snapshot "${CMAKE_CURRENT_BINARY_DIR}/distribution-target-settings.txt")
    file(WRITE "${snapshot}" "Target properties (generator expressions retained verbatim)\n")
    foreach(target wolf3d nuked-opl3 wolf3d-win32 wolf3d-sdl3 wolf3d-console SDL3-shared SDL3::SDL3-shared)
        if(TARGET ${target})
            foreach(property TYPE COMPILE_DEFINITIONS COMPILE_OPTIONS INCLUDE_DIRECTORIES LINK_LIBRARIES LINK_OPTIONS LINK_FLAGS C_STANDARD C_STANDARD_REQUIRED C_EXTENSIONS POSITION_INDEPENDENT_CODE MSVC_RUNTIME_LIBRARY INTERFACE_COMPILE_DEFINITIONS INTERFACE_COMPILE_OPTIONS INTERFACE_LINK_LIBRARIES VERSION SOVERSION IMPORTED_LOCATION IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_DEBUG)
                get_target_property(value ${target} ${property})
                if(NOT value MATCHES "-NOTFOUND$")
                    file(APPEND "${snapshot}" "${target}.${property}: ${value}\n")
                endif()
            endforeach()
        endif()
    endforeach()
endfunction()
