# Shared distribution document finalizer; compatible with CMake 3.5.
# Staging must have created DIST afresh. Never run against a source checkout.
if(NOT EXISTS "${DIST}/DOCS/BUILD.TXT" OR NOT EXISTS "${DIST}/DOCS/LICENSES/GPL-2.TXT")
    message(FATAL_ERROR "Incomplete package documentation in ${DIST}")
endif()
set(notices "${DIST}/DOCS/NOTICES.TXT")
file(READ "${ROOT}/packaging/notices/BASE.TXT" text)
file(WRITE "${notices}" "${text}")
foreach(component PORTABLE NUKED DBOPL SDL3 DOS32A)
    set(include_component FALSE)
    if(component STREQUAL "PORTABLE" AND PRODUCT STREQUAL "wolf3d-portable")
        set(include_component TRUE)
    elseif(component STREQUAL "NUKED" AND EXISTS "${DIST}/DOCS/LICENSES/LGPL-21.TXT")
        set(include_component TRUE)
    elseif(component STREQUAL "DBOPL" AND EXISTS "${DIST}/DOCS/DBOPL.TXT")
        set(include_component TRUE)
    elseif(EXISTS "${DIST}/DOCS/LICENSES/${component}.TXT")
        set(include_component TRUE)
    endif()
    if(include_component)
        file(READ "${ROOT}/packaging/notices/${component}.TXT" text)
        file(APPEND "${notices}" "${text}")
    endif()
endforeach()
if(EXISTS "${DIST}/DOCS/DBOPL.TXT")
    file(READ "${DIST}/DOCS/DBOPL.TXT" text)
    file(APPEND "${notices}" "\n${text}\n")
    file(REMOVE "${DIST}/DOCS/DBOPL.TXT")
endif()
if(EXISTS "${DIST}/DOCS/ENGINE.TXT")
    file(READ "${DIST}/DOCS/ENGINE.TXT" text)
    file(APPEND "${DIST}/DOCS/BUILD.TXT" "\n===== Engine summary =====\n${text}\n")
    file(REMOVE "${DIST}/DOCS/ENGINE.TXT")
endif()
file(APPEND "${DIST}/README.TXT" "\nDocumentation\n-------------\nDOCS/BUILD.TXT records every build option and exact source revisions.\nThis package contains GPL software; see DOCS/NOTICES.TXT for component\nlicenses, source information and replacement instructions, and\nDOCS/LICENSES for the complete license texts and copyright notices.\nKeep these documents with the distribution.\n")
